channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=23.3.2
- pip:
  - python-snappy==0.6.1
  - jmespath==0.9.5
  - scikit-learn==1.2.0
  - partd==1.1.0
  - sparse==0.13.0
  - cloudpickle==1.6.0
  - multidict==4.7.6
  - frozendict==2.3.4
  - s3fs==0.4.2
  - dill==0.3.5.1
  - pyarrow==14.0.2
  - yarl==1.9.4
  - networkx==2.8.8
  - statsd==3.3.0
  - pandas==1.3.5
  - pyyaml==6.0.1
  - six==1.14.0
  - xgboost==1.1.0
  - typing-extensions==4.10.0
  - docstring-parser==0.13
  - pillow==10.3.0
  - python-dateutil==2.8.2
  - protobuf==3.19.6
  - pyjwt==2.8.0
  - botocore==1.34.2
  - requests==2.31.0
  - threadpoolctl==3.1.0
  - tqdm==4.64.1
  - tenacity==6.3.1
  - idna==3.7
  - psutil==5.9.8
  - pytz==2019.3
  - anyio==3.5.0
  - SQLAlchemy==1.4.44
  - async-timeout==4.0.2
  - locket==1.0.0
  - attrs==23.1.0
  - sniffio==1.2.0
  - charset-normalizer==2.0.6
  - s3transfer==0.9.0
  - matplotlib==3.7.3
  - toolz==0.12.0
  - aiohttp==3.9.5
  - filelock==3.7.0
  - urllib3==1.26.18
  - opencv-python-headless==4.8.1.78
  - regex==2022.1.18
  - fsspec[http]==2023.12.2
  - distributed==2022.4.0
  - certifi==2024.2.2
  - joblib==1.2.0
  - packaging==23.2
  - wheels/snorkelflowmlflow-0.91.19-py3-none-any.whl
  - cramjam==2.7.0
  - aiosignal==1.2.0
  - numpy==1.22.2
  - mlflow==2.12.1
  - boto3==1.34.2
  - starlette==0.36.3
  - frozenlist==1.4.0
  - scipy==1.10.1
  - pydantic==1.10.14
  - pyre2==0.3.6
  - setproctitle==1.2.2
  - dask[array,dataframe]==2022.4.0
  - fastparquet==0.8.3
name: mlflow-env
